make parallel testing optional

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,6 +1,7 @@
 #!/bin/bash
 #
 # ARG_OPTIONAL_BOOLEAN([tear-down],[t],[tear down the docker containers after testing],[on])
+# ARG_OPTIONAL_BOOLEAN([parallel],[p],[run tests in parallel (GNU Parallel required)],[on])
 # ARG_HELP([run tests])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
@@ -21,20 +22,22 @@ die()
 
 begins_with_short_option()
 {
-    local first_option all_short_options='th'
+    local first_option all_short_options='tph'
     first_option="${1:0:1}"
     test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_tear_down="on"
+_arg_parallel="on"
 
 
 print_help()
 {
     printf '%s\n' "run tests"
-    printf 'Usage: %s [-t|--(no-)tear-down] [-h|--help]\n' "$0"
+    printf 'Usage: %s [-t|--(no-)tear-down] [-p|--(no-)parallel] [-h|--help]\n' "$0"
     printf '\t%s\n' "-t, --tear-down, --no-tear-down: tear down the docker containers after testing (on by default)"
+    printf '\t%s\n' "-p, --parallel, --no-parallel: run tests in parallel (GNU Parallel required) (on by default)"
     printf '\t%s\n' "-h, --help: Prints help"
 }
 
@@ -55,6 +58,18 @@ parse_commandline()
                 if test -n "$_next" -a "$_next" != "$_key"
                 then
                     { begins_with_short_option "$_next" && shift && set -- "-t" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+                fi
+                ;;
+            -p|--no-parallel|--parallel)
+                _arg_parallel="on"
+                test "${1:0:5}" = "--no-" && _arg_parallel="off"
+                ;;
+            -p*)
+                _arg_parallel="on"
+                _next="${_key##-p}"
+                if test -n "$_next" -a "$_next" != "$_key"
+                then
+                    { begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
                 fi
                 ;;
             -h|--help)
@@ -80,17 +95,30 @@ parse_commandline "$@"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 
-pdk validate --parallel &&
-pdk test unit --parallel &&
+if [[ $_arg_parallel == 'on' ]]
+then
+    pdk validate --parallel &&
+    pdk test unit --parallel
+else
+    pdk validate &&
+    pdk test unit
+fi &&
 {
     pdk bundle exec rake litmus:tear_down
     pdk bundle exec rake 'litmus:provision_list[default]' &&
     pdk bundle exec rake litmus:install_agent &&
     pdk bundle exec rake litmus:install_module &&
-    parallel \
-    'TARGET_HOST=localhost:222{1} pdk bundle exec rspec spec/acceptance/bind_{2}spec.rb' \
-    ::: 2 3 4 :::+ '' backport_ resolvconf_service_ &&
-    if [[ $_arg_tear_down == "on" ]]
+    if [[ $_arg_parallel == 'on' ]]
+    then
+        parallel \
+        'TARGET_HOST=localhost:222{1} pdk bundle exec rspec spec/acceptance/bind_{2}spec.rb' \
+        ::: 2 3 4 :::+ '' backport_ resolvconf_service_
+    else
+        TARGET_HOST=localhost:2222 pdk bundle exec rspec spec/acceptance/bind_spec.rb &&
+        TARGET_HOST=localhost:2223 pdk bundle exec rspec spec/acceptance/bind_backport_spec.rb &&
+        TARGET_HOST=localhost:2224 pdk bundle exec rspec spec/acceptance/bind_resolvconf_service_spec.rb
+    fi &&
+    if [[ $_arg_tear_down == 'on' ]]
     then
         pdk bundle exec rake litmus:tear_down
     fi
